// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package com.yhl.cast.client.proto;

public final class UserProto {
  private UserProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:User)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string name = 1;</code>
     */
    String getName();
    /**
     * <code>optional string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional string email = 2;</code>
     */
    String getEmail();
    /**
     * <code>optional string email = 2;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>optional string phone = 3;</code>
     */
    String getPhone();
    /**
     * <code>optional string phone = 3;</code>
     */
    com.google.protobuf.ByteString
        getPhoneBytes();

    /**
     * <code>optional int32 age = 4;</code>
     */
    int getAge();

    /**
     * <code>optional int32 sex = 5;</code>
     */
    int getSex();
  }
  /**
   * Protobuf type {@code User}
   */
  public  static final class User extends
      com.google.protobuf.GeneratedMessageLite<
          User, User.Builder> implements
      // @@protoc_insertion_point(message_implements:User)
      UserOrBuilder {
    private User() {
      name_ = "";
      email_ = "";
      phone_ = "";
    }
    public static final int NAME_FIELD_NUMBER = 1;
    private String name_;
    /**
     * <code>optional string name = 1;</code>
     */
    public String getName() {
      return name_;
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(name_);
    }
    /**
     * <code>optional string name = 1;</code>
     */
    private void setName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
    }
    /**
     * <code>optional string name = 1;</code>
     */
    private void clearName() {
      
      name_ = getDefaultInstance().getName();
    }
    /**
     * <code>optional string name = 1;</code>
     */
    private void setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value.toStringUtf8();
    }

    public static final int EMAIL_FIELD_NUMBER = 2;
    private String email_;
    /**
     * <code>optional string email = 2;</code>
     */
    public String getEmail() {
      return email_;
    }
    /**
     * <code>optional string email = 2;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(email_);
    }
    /**
     * <code>optional string email = 2;</code>
     */
    private void setEmail(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      email_ = value;
    }
    /**
     * <code>optional string email = 2;</code>
     */
    private void clearEmail() {
      
      email_ = getDefaultInstance().getEmail();
    }
    /**
     * <code>optional string email = 2;</code>
     */
    private void setEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      email_ = value.toStringUtf8();
    }

    public static final int PHONE_FIELD_NUMBER = 3;
    private String phone_;
    /**
     * <code>optional string phone = 3;</code>
     */
    public String getPhone() {
      return phone_;
    }
    /**
     * <code>optional string phone = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPhoneBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(phone_);
    }
    /**
     * <code>optional string phone = 3;</code>
     */
    private void setPhone(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      phone_ = value;
    }
    /**
     * <code>optional string phone = 3;</code>
     */
    private void clearPhone() {
      
      phone_ = getDefaultInstance().getPhone();
    }
    /**
     * <code>optional string phone = 3;</code>
     */
    private void setPhoneBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      phone_ = value.toStringUtf8();
    }

    public static final int AGE_FIELD_NUMBER = 4;
    private int age_;
    /**
     * <code>optional int32 age = 4;</code>
     */
    public int getAge() {
      return age_;
    }
    /**
     * <code>optional int32 age = 4;</code>
     */
    private void setAge(int value) {
      
      age_ = value;
    }
    /**
     * <code>optional int32 age = 4;</code>
     */
    private void clearAge() {
      
      age_ = 0;
    }

    public static final int SEX_FIELD_NUMBER = 5;
    private int sex_;
    /**
     * <code>optional int32 sex = 5;</code>
     */
    public int getSex() {
      return sex_;
    }
    /**
     * <code>optional int32 sex = 5;</code>
     */
    private void setSex(int value) {
      
      sex_ = value;
    }
    /**
     * <code>optional int32 sex = 5;</code>
     */
    private void clearSex() {
      
      sex_ = 0;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!name_.isEmpty()) {
        output.writeString(1, getName());
      }
      if (!email_.isEmpty()) {
        output.writeString(2, getEmail());
      }
      if (!phone_.isEmpty()) {
        output.writeString(3, getPhone());
      }
      if (age_ != 0) {
        output.writeInt32(4, age_);
      }
      if (sex_ != 0) {
        output.writeInt32(5, sex_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!name_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getName());
      }
      if (!email_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getEmail());
      }
      if (!phone_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getPhone());
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, age_);
      }
      if (sex_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, sex_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(User prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          User, Builder> implements
        // @@protoc_insertion_point(builder_implements:User)
        UserOrBuilder {
      // Construct using com.example.cast.proto.UserProto.User.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional string name = 1;</code>
       */
      public String getName() {
        return instance.getName();
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        return instance.getNameBytes();
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setName(
          String value) {
        copyOnWrite();
        instance.setName(value);
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder clearName() {
        copyOnWrite();
        instance.clearName();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNameBytes(value);
        return this;
      }

      /**
       * <code>optional string email = 2;</code>
       */
      public String getEmail() {
        return instance.getEmail();
      }
      /**
       * <code>optional string email = 2;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        return instance.getEmailBytes();
      }
      /**
       * <code>optional string email = 2;</code>
       */
      public Builder setEmail(
          String value) {
        copyOnWrite();
        instance.setEmail(value);
        return this;
      }
      /**
       * <code>optional string email = 2;</code>
       */
      public Builder clearEmail() {
        copyOnWrite();
        instance.clearEmail();
        return this;
      }
      /**
       * <code>optional string email = 2;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setEmailBytes(value);
        return this;
      }

      /**
       * <code>optional string phone = 3;</code>
       */
      public String getPhone() {
        return instance.getPhone();
      }
      /**
       * <code>optional string phone = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPhoneBytes() {
        return instance.getPhoneBytes();
      }
      /**
       * <code>optional string phone = 3;</code>
       */
      public Builder setPhone(
          String value) {
        copyOnWrite();
        instance.setPhone(value);
        return this;
      }
      /**
       * <code>optional string phone = 3;</code>
       */
      public Builder clearPhone() {
        copyOnWrite();
        instance.clearPhone();
        return this;
      }
      /**
       * <code>optional string phone = 3;</code>
       */
      public Builder setPhoneBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPhoneBytes(value);
        return this;
      }

      /**
       * <code>optional int32 age = 4;</code>
       */
      public int getAge() {
        return instance.getAge();
      }
      /**
       * <code>optional int32 age = 4;</code>
       */
      public Builder setAge(int value) {
        copyOnWrite();
        instance.setAge(value);
        return this;
      }
      /**
       * <code>optional int32 age = 4;</code>
       */
      public Builder clearAge() {
        copyOnWrite();
        instance.clearAge();
        return this;
      }

      /**
       * <code>optional int32 sex = 5;</code>
       */
      public int getSex() {
        return instance.getSex();
      }
      /**
       * <code>optional int32 sex = 5;</code>
       */
      public Builder setSex(int value) {
        copyOnWrite();
        instance.setSex(value);
        return this;
      }
      /**
       * <code>optional int32 sex = 5;</code>
       */
      public Builder clearSex() {
        copyOnWrite();
        instance.clearSex();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:User)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new User();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          User other = (User) arg1;
          name_ = visitor.visitString(!name_.isEmpty(), name_,
              !other.name_.isEmpty(), other.name_);
          email_ = visitor.visitString(!email_.isEmpty(), email_,
              !other.email_.isEmpty(), other.email_);
          phone_ = visitor.visitString(!phone_.isEmpty(), phone_,
              !other.phone_.isEmpty(), other.phone_);
          age_ = visitor.visitInt(age_ != 0, age_,
              other.age_ != 0, other.age_);
          sex_ = visitor.visitInt(sex_ != 0, sex_,
              other.sex_ != 0, other.sex_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  name_ = s;
                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();

                  email_ = s;
                  break;
                }
                case 26: {
                  String s = input.readStringRequireUtf8();

                  phone_ = s;
                  break;
                }
                case 32: {

                  age_ = input.readInt32();
                  break;
                }
                case 40: {

                  sex_ = input.readInt32();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (User.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:User)
    private static final User DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new User();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static User getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<User> PARSER;

    public static com.google.protobuf.Parser<User> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
